from pathlib import Path

ROOT=Path('/home/ubuntu/lockplus15-rootless/themes/folder-themes')

SHARED='''
:root{color-scheme:dark}html,body{background:#080b12;-webkit-font-smoothing:antialiased;text-rendering:geometricPrecision}body{overscroll-behavior:none}#theme-root{width:375px;height:667px;isolation:isolate;overflow:hidden;background:#101820}#theme-root:after{content:"";position:absolute;inset:0;pointer-events:none;z-index:900;background:linear-gradient(180deg,rgba(0,0,0,.08),transparent 28%,transparent 72%,rgba(0,0,0,.18));mix-blend-mode:multiply}.theme-element{will-change:transform,opacity}.dynamic{letter-spacing:.02em}.dynamic.clock,.dynamic.word-clock{font-variant-numeric:tabular-nums;line-height:.92}.dynamic.date{text-transform:uppercase;letter-spacing:.14em}.theme-element img{display:block;width:100%;height:100%;object-fit:cover}.theme-element[style*="z-index:-100"]{pointer-events:none}.theme-element[style*="z-index:0"]{filter:saturate(1.04) contrast(1.02)}
'''

STYLES={
'animated-art-gallery':'''#theme-root{background:#eee5d7;color:#36241b}.wallpaper{background:linear-gradient(145deg,#cda883,#f7efe2)!important;opacity:1}.dynamic.clock{font-family:Georgia,serif;font-size:42px!important;letter-spacing:-.04em;color:#4b2d1e!important}.dynamic.date{font-family:-apple-system,sans-serif;font-size:12px!important;letter-spacing:.12em}.theme-element[id="galleryHeader"]{font-weight:700;letter-spacing:.22em;text-transform:uppercase}.theme-element[id="gallerySubhead"]{letter-spacing:.14em}.theme-element[id="labelBacking"]{border-radius:18px!important;box-shadow:0 8px 24px rgba(75,45,30,.18);background:rgba(251,247,238,.88)!important;backdrop-filter:blur(8px)}.theme-element[id="galleryAnimation"]{border-radius:16px;overflow:hidden;box-shadow:0 18px 40px rgba(75,45,30,.22)}''',
'brushstroke-time':'''#theme-root{background:#e9e5d8;color:#173dad}.wallpaper{background:radial-gradient(circle at 70% 20%,#fffdf6,#d9d2c0)!important}.dynamic.brushstroke{font-family:Georgia,serif;font-style:italic;font-size:62px!important;letter-spacing:-.04em;text-shadow:2px 3px 0 rgba(23,61,173,.12);color:#173dad!important}.theme-element[id="paper"]{opacity:.92}.theme-element[id="paintedTimeAndStudy"]{filter:drop-shadow(0 12px 15px rgba(23,61,173,.18))}''',
'cat-hat-side-clock':'''#theme-root{background:#08152d;color:#f8e8c2}.theme-element[id="catBackground"]{filter:saturate(1.12) contrast(1.04)}.dynamic.clock{font-family:Georgia,serif;font-size:58px!important;color:#f4d08b!important;text-shadow:2px 2px 0 #b52d32,3px 5px 8px rgba(0,0,0,.48);transform:rotate(90deg) translateZ(0)}.dynamic.date{font-size:14px!important;color:#f8e8c2!important;text-shadow:0 2px 3px rgba(0,0,0,.65)}''',
'cookie-monster-lock':'''#theme-root{background:#f4c06a;color:#8a4b2a}.wallpaper{background:linear-gradient(160deg,#f8d787,#ef9e51)!important}.dynamic.clock{font-family:Georgia,serif;font-weight:900;font-size:74px!important;letter-spacing:-.06em;color:#8a4b2a!important;text-shadow:2px 3px 0 #f9df9c,0 7px 12px rgba(89,45,20,.2)}.dynamic.date{font-weight:700;color:#8a4b2a!important;letter-spacing:.1em}.theme-element[id="cookie-clock-texture"]{border-radius:50%;filter:saturate(1.12)}''',
'framed-parking':'''#theme-root{background:#d9d2c5;color:#191919}.wallpaper{background:linear-gradient(155deg,#b8b0a4,#f0ece4)!important}.dynamic.word-clock{font-family:Georgia,serif;font-size:31px!important;line-height:1.02;color:#0d0d0d!important;letter-spacing:.08em}.dynamic.date{font-size:12px!important;color:#565656!important;letter-spacing:.12em}.theme-element[id="outerFrame"]{border:1px solid rgba(25,25,25,.32)!important;box-shadow:0 16px 30px rgba(25,25,25,.18)}.theme-element[id="whiteMat"]{background:rgba(255,255,255,.78)!important}.theme-element[id="framedAnimation"]{box-shadow:0 10px 20px rgba(25,25,25,.15)}''',
'move-the-image':'''#theme-root{background:#dbc4a7;color:#2b190f}.wallpaper{background:linear-gradient(145deg,#bd8b5b,#f1dfc9)!important}.dynamic.word-clock{font-family:Georgia,serif;font-size:29px!important;line-height:1.05;color:#17110d!important;letter-spacing:.08em}.dynamic.date{color:#66584e!important;letter-spacing:.12em}.theme-element[id="woodOuter"]{border-radius:8px!important;box-shadow:0 18px 35px rgba(43,25,15,.24)}.theme-element[id="woodHighlight"]{border-radius:6px!important}.theme-element[id="woodInset"]{border-radius:4px!important}.theme-element[id="framedAnimation"]{filter:sepia(.12) saturate(1.1)}.theme-element[id="quoteBacking"]{border-radius:12px!important;box-shadow:0 10px 24px rgba(43,25,15,.14);background:rgba(255,255,255,.78)!important}''',
'planet-globe-animated-gif':'''#theme-root{background:#02050d;color:#fff}.theme-element[id="globe"]{filter:saturate(1.18) contrast(1.08);animation:planetFloat 8s ease-in-out infinite}.dynamic.clock{font-family:-apple-system,sans-serif;font-size:80px!important;font-weight:200;color:#fff!important;letter-spacing:-.07em;text-shadow:0 5px 22px rgba(79,164,255,.35)}.dynamic.date{font-size:13px!important;letter-spacing:.18em;color:rgba(255,255,255,.86)!important}@keyframes planetFloat{0%,100%{transform:translateX(-50%) scale(1)}50%{transform:translateX(-50%) scale(1.025)}}''',
'pulse-timeline':'''#theme-root{background:#071817;color:#3fffb8}.wallpaper{background:radial-gradient(circle at 50% 30%,#163d38,#061211)!important}.theme-element[id="monitorPanel"]{border:1px solid rgba(63,255,184,.55)!important;border-radius:18px!important;box-shadow:0 0 35px rgba(63,255,184,.14),inset 0 0 24px rgba(63,255,184,.06);background:rgba(4,30,28,.55)!important}.dynamic.pulse{border:0!important;color:#3fffb8!important;filter:drop-shadow(0 0 8px rgba(63,255,184,.75));animation:pulseGlow 2.2s ease-in-out infinite}@keyframes pulseGlow{50%{opacity:.72;filter:drop-shadow(0 0 16px rgba(63,255,184,.95))}}''',
'white-word-wheel':'''#theme-root{background:#eee8dc;color:#191919}.wallpaper{background:linear-gradient(160deg,#c4b9a7,#f8f4eb)!important}.dynamic.word-clock{font-family:Georgia,serif;font-size:31px!important;line-height:1.03;color:#0d0d0d!important;letter-spacing:.08em}.dynamic.date{font-size:12px!important;color:#565656!important;letter-spacing:.12em}.theme-element[id="hamsterWheel"]{border-radius:50%;filter:drop-shadow(0 16px 18px rgba(25,25,25,.2));animation:wheelTurn 18s linear infinite}@keyframes wheelTurn{to{transform:translateX(-50%) rotate(360deg)}}.theme-element[id="caption"]{letter-spacing:.2em;font-weight:700}'''
}

for theme, extra in STYLES.items():
    d=ROOT/theme
    if not d.is_dir(): continue
    css=d/'style.css'
    base=css.read_text() if css.exists() else ''
    css.write_text(base+'\n'+SHARED+'\n'+extra+'\n')
    js=d/'script.js'
    if js.exists():
        current=js.read_text()
        if 'orientationchange' not in current:
            current += '\nwindow.addEventListener("resize",()=>document.documentElement.style.setProperty("--viewport-scale",Math.min(innerWidth/375,innerHeight/667)));\n'
        js.write_text(current)
print('polished', ', '.join(sorted(STYLES)))
